### ISSUE TITLE
0.9.3: java.lang.NoSuchFieldError: INSTANCE on project reopen with default plugin settings.

### ISSUE THREAD

**Issue by smheaton** [dboissier/jenkins-control-plugin#100]
And I am sorry to pile on (and I hugely appreciate all of your work on this plugin), but on a new project, I also get a slightly different error.

To reproduce:

1.  In IDEA 15.0 with the Jenkins Control Plugin v0.9.3 installed, create a new Java project.
2.  Use the IJ template to create a new command line app.
3.  Leave the Jenkins plugin settings set to the default:  (e.g. leave http://dummyjenkinsserver in place).
4.  Close IDEA.
5.  Reopen IDEA and select the project you just created to reopen it.

At this point, the following error occurs for me:

org.codinjutsu.tools.jenkins.JenkinsComponent@1b2062a: INSTANCE
java.lang.NoSuchFieldError: INSTANCE
	at org.codinjutsu.tools.jenkins.view.JenkinsWidget.createStatusIcon(JenkinsWidget.java:83)
	at org.codinjutsu.tools.jenkins.view.JenkinsWidget.<init>(JenkinsWidget.java:49)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
	at org.picocontainer.defaults.ConstructorInjectionComponentAdapter$1.run(ConstructorInjectionComponentAdapter.java:220)
	at org.picocontainer.defaults.ThreadLocalCyclicDependencyGuard.observe(ThreadLocalCyclicDependencyGuard.java:53)
	at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:248)
	at com.intellij.util.pico.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:59)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:232)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:246)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:212)
	at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:46)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:41)
	at org.codinjutsu.tools.jenkins.view.JenkinsWidget.getInstance(JenkinsWidget.java:44)
	at org.codinjutsu.tools.jenkins.JenkinsWindowManager.<init>(JenkinsWindowManager.java:58)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
	at org.picocontainer.defaults.ConstructorInjectionComponentAdapter$1.run(ConstructorInjectionComponentAdapter.java:220)
	at org.picocontainer.defaults.ThreadLocalCyclicDependencyGuard.observe(ThreadLocalCyclicDependencyGuard.java:53)
	at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:248)
	at com.intellij.util.pico.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:59)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:232)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:246)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:212)
	at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:46)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:41)
	at org.codinjutsu.tools.jenkins.JenkinsWindowManager.getInstance(JenkinsWindowManager.java:42)
	at org.codinjutsu.tools.jenkins.JenkinsComponent.projectOpened(JenkinsComponent.java:54)
	at com.intellij.openapi.project.impl.ProjectImpl.c(ProjectImpl.java:400)
	at com.intellij.openapi.project.impl.ProjectImpl.access$200(ProjectImpl.java:63)
	at com.intellij.openapi.project.impl.ProjectImpl$MyProjectManagerListener.projectOpened(ProjectImpl.java:434)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$1.projectOpened(ProjectManagerImpl.java:97)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.e(ProjectManagerImpl.java:719)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.openProject(ProjectManagerImpl.java:350)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.loadAndOpenProject(ProjectManagerImpl.java:465)
	at com.intellij.ide.impl.ProjectUtil.openProject(ProjectUtil.java:183)
	at com.intellij.ide.RecentProjectsManagerImpl.doOpenProject(RecentProjectsManagerImpl.java:46)
	at com.intellij.ide.ReopenProjectAction.actionPerformed(ReopenProjectAction.java:61)
	at com.intellij.openapi.wm.impl.welcomeScreen.RecentProjectPanel$2.onClick(RecentProjectPanel.java:124)
	at com.intellij.ui.ClickListener$1.mouseReleased(ClickListener.java:73)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6525)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at com.intellij.openapi.wm.impl.welcomeScreen.RecentProjectPanel$MyList.processMouseEvent(RecentProjectPanel.java:352)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:861)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:645)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:380)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by ihorpts** [comment]
The same for me... upgrading the plugin didn't help for IntelliJ 15

**Comment by cezary-butler** [comment]
Please try my build which You can find at: http://programisci.eu/?p=405
If it works for you then we will have to find out what's different between my build and 0.9.3.

**Comment by musicformellons** [comment]
@cezary-butler I had same error message (with Pycharm 5.0), but using your build it now works (at least no error messages...). Thanks!

**Comment by smheaton** [comment]
@cezary-butler Your build fixed my issues as well.  Thanks!

**Comment by dboissier** [comment]
How is Jenkins build?
Under Ubuntu 12.04 64 bits, with maven 2 and jdk 1.7 from oracle. What I understand is the WidgetBar instance from Intellij is not loaded when initializing the JenkinsWidget., so the NPE occurs.

Any way, I will upload the cezari version tonight

**Comment by cezary-butler** [comment]
What I see is not NPE its no such field.
I've seen this previously when building plugin with Idea 15 SDK when
running plugin on Idea 14, and vice versa (Running on 15 but building with
SDK 14).
I'm building plugin using Idea not maven.

P.S. It's not Cezari it's Cezary ;)

2015-11-03 22:52 GMT+01:00 David Boissier <notifications@github.com>:

**Comment by dboissier** [comment]
Hi,

sorry I misread the error.

Something strange happens because I download the Idea 12 IC version and reproduce the steps of Sean and I do not have any error.

@cezary-butler do you agree to upload your version on the jetbrains plugin to unblock the situation for a while?

**Comment by cezary-butler** [comment]
Yes, you can upload my version.

2015-11-04 9:13 GMT+01:00 David Boissier <notifications@github.com>:

**Comment by nicity** [comment]
https://youtrack.jetbrains.com/issue/IDEA-147311

**Comment by dboissier** [comment]
@cezary-butler Done.

**Comment by dboissier** [comment]
Hi,

Build from @cezary-butler has just been uploaded to the Jetbrains plugins repository. You may be able to update it from your IDE

Sorry for the inconvenience (this often happens when new Jetbrains producs are released).

**Comment by smheaton** [comment]
Hey, no problem at all.  I really appreciate all of your work on this and I have to say, I really like using the plugin.  Thanks again!

**Comment by dboissier** [comment]
Hi @smheaton ,

@cezary-butler made robust fix for Idea 14 / 15 compatibility issue

 Could you please test this [SNAPSHOT](https://github.com/dboissier/jenkins-control-plugin/raw/master/snapshot/jenkins-control-plugin-0.9.4-SNAPSHOT-distribution.zip) and tell me if it works on your IDE?

Thanks.

**Comment by smheaton** [comment]
Looks like it is working fine with the latest version (0.9.3-Programisci-2).

**Comment by cezary-butler** [comment]
Previous version would work only on IDEA version that was built with (in this case 15).
New is intended to work on both 15 and 14.

**Comment by smheaton** [comment]
Definitely looks good on 15.

**Comment by dboissier** [comment]
Thanks. I just uploaded 0.9.4 on the Jetbrains plugin repository.
