### ISSUE TITLE
 java.security.cert.CertificateException

### ISSUE THREAD

**Issue by stefaneicher** [dboissier/jenkins-control-plugin#103]
Hi,
I get a 
"Plugin Jenkins Control Plugin was not installed: java.security.cert.CertificateException: No subject alternative DNS name matching programisci.eu found."

if i want to install the newest plugin. I have never seen such an error when installing a plugin before.

Regards Stefan

**Comment by cezary-butler** [comment]
Please submit full exception stack trace.
Do you install or update plugin?

Thank You in advance

**Comment by AnthonyYeracaris** [comment]
Found a stack trace.  This is during update.

[ 145546]   WARN - Settings.impl.PluginDownloader - java.security.cert.CertificateException: No subject alternative DNS name matching programisci.eu found. 
javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: No subject alternative DNS name matching programisci.eu found.
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1884)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:276)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:270)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1341)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:153)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:868)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:804)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1016)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1312)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1339)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1323)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1300)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at com.intellij.util.io.HttpRequests.openConnection(HttpRequests.java:284)
	at com.intellij.util.io.HttpRequests.access$000(HttpRequests.java:52)
	at com.intellij.util.io.HttpRequests$1RequestImpl.getConnection(HttpRequests.java:142)
	at com.intellij.util.io.HttpRequests.createErrorMessage(HttpRequests.java:94)
	at com.intellij.util.io.HttpRequests$1RequestImpl.saveToFile(HttpRequests.java:217)
	at com.intellij.openapi.updateSettings.impl.PluginDownloader$2.process(PluginDownloader.java:255)
	at com.intellij.openapi.updateSettings.impl.PluginDownloader$2.process(PluginDownloader.java:252)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:235)
	at com.intellij.util.io.RequestBuilder.connect(RequestBuilder.java:121)
	at com.intellij.openapi.updateSettings.impl.PluginDownloader.a(PluginDownloader.java:252)
	at com.intellij.openapi.updateSettings.impl.PluginDownloader.prepareToInstall(PluginDownloader.java:149)
	at com.intellij.openapi.updateSettings.impl.UpdateChecker.installPluginUpdates(UpdateChecker.java:612)
	at com.intellij.openapi.updateSettings.impl.PluginUpdateInfoDialog$2.run(PluginUpdateInfoDialog.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:126)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:365)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)
Caused by: java.security.cert.CertificateException: No subject alternative DNS name matching programisci.eu found.
	at sun.security.util.HostnameChecker.matchDNS(HostnameChecker.java:191)
	at sun.security.util.HostnameChecker.match(HostnameChecker.java:93)
	at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:347)
	at sun.security.ssl.AbstractTrustManagerWrapper.checkAdditionalTrust(SSLContextImpl.java:847)
	at sun.security.ssl.AbstractTrustManagerWrapper.checkServerTrusted(SSLContextImpl.java:814)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1323)
	... 39 more

**Comment by stefaneicher** [comment]
Yes , this is the excact same error as I have. I now also found the stacktrace. It is the same as above. Gruss Stefan

**Comment by dboissier** [comment]
Hi,

I ran `git grep 'programisci.eu'` and I got the following resuts:
```
README.md:* [Cezary Butler](https://github.com/cezary-butler) and **Marcin Seroka** from [Programisci](http://programisci.eu/en/) for their contribution to fix and improve this plugin for Idea 14 and 15
src/main/resources/META-INF/plugin.xml:<a href="http://programisci.eu/en/intellij-jenkins-plugin/" > Note </a>
```

The plugin is downloaded from `https://plugin.jetbrains.com` (Secured connection) and in the `plugin .xml` references non secured url `http://programisci.eu/en/intellij-jenkins-plugin)`.

My hypothesis is the `plugin.xml` is read by the Plugin Manager and when it find an url, it tries to resolve it on the fly. If yes, there is a check in the JVM that prevent the security of the connection to be broken because it intends to resolve a non secure url whereas it started from a secured url.

I am not sure I was clear on this point.

Weird, isn't it?

**Comment by cezary-butler** [comment]
I've looked at intellij community source code and it looks like problem appears while trying to download plugin. 
It tries to download it with https from programisci.eu (which is not protected by valid certificate).

Uploading plugin directly to jetbrains repository or to other server having proper certificate should resolve this problem.

**Comment by dboissier** [comment]
Just fixed and thanks @cezary-butler for having found the real root cause.

Because I specified a direct link from programisci.eu instead of uploading from a local distribution (So my hypothesis was wrong ;) ).

@stefaneicher please, retry and tell us if it is ok.

**Comment by AnthonyYeracaris** [comment]
Download successful, thank you.
