### ISSUE TITLE
Favorites broken if job deleted

### ISSUE THREAD

**Issue by palortoff** [dboissier/jenkins-control-plugin#111]
If you set a favorite for a job, and then delete the job on jenkins, the plugin is unable to display the favorite view. 

```
Not found
org.codinjutsu.tools.jenkins.security.AuthenticationException: Not found
	at org.codinjutsu.tools.jenkins.security.DefaultSecurityClient.checkResponse(DefaultSecurityClient.java:145)
	at org.codinjutsu.tools.jenkins.security.DefaultSecurityClient.runMethod(DefaultSecurityClient.java:124)
	at org.codinjutsu.tools.jenkins.security.DefaultSecurityClient.execute(DefaultSecurityClient.java:68)
	at org.codinjutsu.tools.jenkins.logic.RequestManager.loadJob(RequestManager.java:150)
	at org.codinjutsu.tools.jenkins.logic.RequestManager.loadFavoriteJobs(RequestManager.java:222)
	at org.codinjutsu.tools.jenkins.view.BrowserPanel.loadJobs(BrowserPanel.java:455)
	at org.codinjutsu.tools.jenkins.view.BrowserPanel.access$700(BrowserPanel.java:65)
```

Workaround:
If you delete the favorites in workspace.xml, favorite view is working again.

**Comment by dboissier** [comment]
Hi,

thx for reporting this bug.
