### ISSUE TITLE
NullPointerException in Jenkins Control Plugin

### ISSUE THREAD

**Issue by dbeuve** [dboissier/jenkins-control-plugin#122]
I am developping with the following release of Intellij

IntelliJ IDEA 2016.1.2
Build #IC-145.972, built on May 14, 2016
JRE: 1.8.0_76-release-b47 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

I tried to install the version 0.9.7 of the Jenkins Control Plugin. And at first start I received the following NPE:

null
java.lang.NullPointerException
    at org.codinjutsu.tools.jenkins.model.Build.getStateIcon(Build.java:87)
    at org.codinjutsu.tools.jenkins.model.Job.getStateIcon(Job.java:75)
    at org.codinjutsu.tools.jenkins.view.JenkinsTreeRenderer.customizeCellRenderer(JenkinsTreeRenderer.java:64)
    at com.intellij.ui.ColoredTreeCellRenderer.getTreeCellRendererComponent(ColoredTreeCellRenderer.java:116)
    at javax.swing.plaf.basic.BasicTreeUI$NodeDimensionsHandler.getNodeDimensions(BasicTreeUI.java:2807)
    at javax.swing.tree.AbstractLayoutCache.getNodeDimensions(AbstractLayoutCache.java:492)
    at javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.updatePreferredSize(VariableHeightLayoutCache.java:1360)
    at javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.expand(VariableHeightLayoutCache.java:1496)
    at javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.expand(VariableHeightLayoutCache.java:1288)
    at javax.swing.tree.VariableHeightLayoutCache.rebuild(VariableHeightLayoutCache.java:743)
    at javax.swing.tree.VariableHeightLayoutCache.treeStructureChanged(VariableHeightLayoutCache.java:644)
    at javax.swing.plaf.basic.BasicTreeUI$Handler.treeStructureChanged(BasicTreeUI.java:3917)
    at javax.swing.tree.DefaultTreeModel.fireTreeStructureChanged(DefaultTreeModel.java:580)
    at javax.swing.tree.DefaultTreeModel.nodeStructureChanged(DefaultTreeModel.java:365)
    at org.codinjutsu.tools.jenkins.view.BrowserPanel$4.run(BrowserPanel.java:203)
    at org.codinjutsu.tools.jenkins.util.GuiUtil.runInSwingThread(GuiUtil.java:50)
    at org.codinjutsu.tools.jenkins.view.BrowserPanel.setSortedByStatus(BrowserPanel.java:200)
    at org.codinjutsu.tools.jenkins.view.BrowserPanel.fillJobTree(BrowserPanel.java:497)
    at org.codinjutsu.tools.jenkins.view.BrowserPanel.access$900(BrowserPanel.java:65)
    at org.codinjutsu.tools.jenkins.view.BrowserPanel$LoadSelectedViewJob$1.run(BrowserPanel.java:581)
    at org.codinjutsu.tools.jenkins.util.GuiUtil.runInSwingThread(GuiUtil.java:50)
    at org.codinjutsu.tools.jenkins.view.BrowserPanel$LoadSelectedViewJob.onSuccess(BrowserPanel.java:578)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$1$2.run(ProgressManagerImpl.java:153)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:345)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:329)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:857)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:658)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by dboissier** [comment]
Hi,

could you please run the followings urls from your browser (once you are authenticated if needed) and send me the output results:
`http://<jenkins_url>/<Your_View>/api/json?tree=nodeName,nodeDescription,primaryView%5Bname,url%5D,views%5Bname,url,views%5Bname,url%5D%5D`

`http://<jenkins_url>/<job_name>/api/json?tree=name,displayName,url,color,buildable,inQueue,healthReport%5Bdescription,iconUrl%5D,lastBuild%5Bid,url,building,result,number%5D,property%5BparameterDefinitions%5Bname,type,defaultParameterValue%5Bvalue%5D,choices%5D%5D`

Remove confidential data if needed.

Thanks

**Comment by dbeuve** [comment]
Hi David,
For the 2 urls you sent me here are the results. Hope these results will the ones you were expecting

For Url 1{

    "primaryView": {
        "name": "All",
        "url": "https://COMPANY_URL/jenkins/view/00-Products/job/PRODUCT/"
    },
    "views": [
        {
            "name": "All",
            "url": "https://COMPANY_URL/jenkins/view/00-Products/job/PRODUCT/"
        },
        {
            "name": "OPF_DEV",
            "url": "https://COMPANY_URL/jenkins/view/00-Products/job/PRODUCT/view/PROD-DEV"
        }
    ]

}

For url 2:{

    "displayName": "JENKINS_JOB_NAME",
    "name": "JENKINS_JOB_NAME",
    "url": "https://COMPANY_URL/jenkins/job/PRODUCT/job/PRODUCT_VERSION/job/JENKINS_JOB_NAME/",
    "buildable": true,
    "color": "blue",
    "healthReport": [
        {
            "description": "Test Result: 0 tests failing out of a total of 1,001 tests.",
            "iconUrl": "health-80plus.png"
        },
        {
            "description": "Build stability: No recent builds failed.",
            "iconUrl": "health-80plus.png"
        }
    ],
    "inQueue": false,
    "lastBuild": {
        "building": false,
        "id": "2016-06-14_09-23-12",
        "number": 820,
        "result": "SUCCESS",
        "url": "https://COMPANY_URL/jenkins/job/PRODUCT/job/PRODUCT_VERSION/job/JENKINS_JOB_NAME/820/"
    },
    "property": [
        { }
    ]

}
Kind Regards
Daniel beuve-Mery


    Le Lundi 13 juin 2016 17h31, David Boissier <notifications@github.com> a écrit :
 

 Hi,could you please run the followings urls from your browser (once you are authenticated if needed) and send me the output results:
http://<jenkins_url>/<Your_View>/api/json?tree=nodeName,nodeDescription,primaryView%5Bname,url%5D,views%5Bname,url,views%5Bname,url%5D%5Dhttp://<jenkins_url>/<job_name>/api/json?tree=name,displayName,url,color,buildable,inQueue,healthReport%5Bdescription,iconUrl%5D,lastBuild%5Bid,url,building,result,number%5D,property%5BparameterDefinitions%5Bname,type,defaultParameterValue%5Bvalue%5D,choices%5D%5DRemove confidential data if needed.Thanks—

**Comment by golauty** [comment]
I have the same Null pointer Exception, has this something to do with using the Jenkins 2?

**Comment by TobseF** [comment]
Same NPE issue here with Jenkins 2.13.

**Comment by tharindu1st** [comment]
NPE occur while retrieving status


null
java.lang.NullPointerException
	at org.codinjutsu.tools.jenkins.model.Build.getStateIcon(Build.java:87)
	at org.codinjutsu.tools.jenkins.model.Job.getStateIcon(Job.java:75)
	at org.codinjutsu.tools.jenkins.view.JenkinsTreeRenderer.customizeCellRenderer(JenkinsTreeRenderer.java:64)
	at com.intellij.ui.ColoredTreeCellRenderer.getTreeCellRendererComponent(ColoredTreeCellRenderer.java:116)
	at javax.swing.plaf.basic.BasicTreeUI$NodeDimensionsHandler.getNodeDimensions(BasicTreeUI.java:2807)
	at javax.swing.tree.AbstractLayoutCache.getNodeDimensions(AbstractLayoutCache.java:492)
	at javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.updatePreferredSize(VariableHeightLayoutCache.java:1360)
	at javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.expand(VariableHeightLayoutCache.java:1487)
	at javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.expand(VariableHeightLayoutCache.java:1288)
	at javax.swing.tree.VariableHeightLayoutCache.rebuild(VariableHeightLayoutCache.java:743)
	at javax.swing.tree.VariableHeightLayoutCache.treeStructureChanged(VariableHeightLayoutCache.java:644)
	at javax.swing.plaf.basic.BasicTreeUI$Handler.treeStructureChanged(BasicTreeUI.java:3917)
	at javax.swing.tree.DefaultTreeModel.fireTreeStructureChanged(DefaultTreeModel.java:580)
	at javax.swing.tree.DefaultTreeModel.nodeStructureChanged(DefaultTreeModel.java:365)
	at org.codinjutsu.tools.jenkins.view.BrowserPanel$4.run(BrowserPanel.java:203)
	at org.codinjutsu.tools.jenkins.util.GuiUtil.runInSwingThread(GuiUtil.java:50)
	at org.codinjutsu.tools.jenkins.view.BrowserPanel.setSortedByStatus(BrowserPanel.java:200)
	at org.codinjutsu.tools.jenkins.view.BrowserPanel.fillJobTree(BrowserPanel.java:497)
	at org.codinjutsu.tools.jenkins.view.BrowserPanel.access$900(BrowserPanel.java:65)
	at org.codinjutsu.tools.jenkins.view.BrowserPanel$LoadSelectedViewJob$1.run(BrowserPanel.java:581)
	at org.codinjutsu.tools.jenkins.util.GuiUtil.runInSwingThread(GuiUtil.java:50)
	at org.codinjutsu.tools.jenkins.view.BrowserPanel$LoadSelectedViewJob.onSuccess(BrowserPanel.java:578)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1$2.run(ProgressManagerImpl.java:153)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:345)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:329)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:857)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:658)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by roni-frantchi** [comment]
Same NPE here. Jenkins 2.34 IDEA 2016.3
