### ISSUE TITLE
PHPStorm 8 with JRE 1.8 Handshake failed

### ISSUE THREAD

**Issue by rehoehle** [dboissier/jenkins-control-plugin#89]
Hello,

for some reasons i have changed the Java version for PHPStorm to Version 8. After the change to 1.7 and 1.8 the Jenkins Plugin isn't working anymore. 

```
IO Error during method execution 'xxxxxxxxx/api/json?tree=nodeName': Received fatal alert: handshake_failure
org.codinjutsu.tools.jenkins.exception.ConfigurationException: IO Error during method execution 'https://deployment.free-life-project.de/api/json?tree=nodeName': Received fatal alert: handshake_failure
	at org.codinjutsu.tools.jenkins.security.BasicSecurityClient.doAuthentication(BasicSecurityClient.java:78)
	at org.codinjutsu.tools.jenkins.security.BasicSecurityClient.connect(BasicSecurityClient.java:47)
	at org.codinjutsu.tools.jenkins.logic.RequestManager.authenticate(RequestManager.java:156)
	at org.codinjutsu.tools.jenkins.view.BrowserPanel.reloadConfiguration(BrowserPanel.java:337)
	at org.codinjutsu.tools.jenkins.view.BrowserPanel.init(BrowserPanel.java:363)
	at org.codinjutsu.tools.jenkins.JenkinsWindowManager$1.run(JenkinsWindowManager.java:72)
	at com.intellij.ide.startup.impl.StartupManagerImpl.b(StartupManagerImpl.java:295)
	at com.intellij.ide.startup.impl.StartupManagerImpl.a(StartupManagerImpl.java:287)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.java:166)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$6$2.run(ProjectManagerImpl.java:451)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:744)
	at java.awt.EventQueue.access$400(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.awt.EventQueue$3.run(EventQueue.java:691)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:714)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:748)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:577)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:384)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:1991)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1104)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1343)
	at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:728)
	at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:123)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at org.apache.commons.httpclient.HttpConnection.flushRequestOutputStream(HttpConnection.java:828)
	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.flushRequestOutputStream(MultiThreadedHttpConnectionManager.java:1565)
	at org.apache.commons.httpclient.HttpMethodBase.writeRequest(HttpMethodBase.java:2116)
	at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1096)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:398)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
	at org.codinjutsu.tools.jenkins.security.BasicSecurityClient.doAuthentication(BasicSecurityClient.java:69)
	... 26 more
```

With Java 1.6 its working. But the problem on Mac is that you have Retina Support on Java 1.7 and never. So i have changed the version. Perhaps you have some tipps to solve that problem.

**Comment by cezary-butler** [comment]
Try this https://github.com/Programisci/jenkins-control-plugin/wiki/Problems-with-ssl-certificates-when-running-on-Java-7-or-later
It works for me.
Unformtulatelly there is no reasonable way to fix this within the plugin code.

**Comment by rehoehle** [comment]
The solution was very simple in the end. I had a very strong cypher configuration. I've added some more cyphers to connect. Then the Handshake is working well. For Nginx i use the following. 

    ssl_ciphers     ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:!aNULL:!MD5:!DSS;
